### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by tute** [adam12/phoenix_mtm#1]
Hi! Thanks for sharing your code. I just copied it into my app and it works well. I did the following changes:
1. I added a third argument to the helper's `Enum.reduce`, so that I can mark certain checkboxes as `disabled`.
2. In `cast_collection` I return the previous value instead of an empty array, so that a change that doesn't include that relation doesn't reset it.
3. The helper's `Enum.reduce` doesn't need an accumulator, and can be simplified to a `map`.
4. If I always pipe a changeset into `PhoenixMTM.Changeset.cast_collection(:tags, App.Repo, App.Tag)`, I need to `preload(:tags)` on every use of the changeset, even when if that relationship is not updated. I was surprised when the unit tests for my model for `changeset.valid?` were failing when there is no specific change that would require that relationship. Is this expected?

Thank you again for your code!

Tute.

**Comment by adam12** [comment]
Thanks for the feedback.

> I added a third argument to the helper's Enum.reduce, so that I can mark certain checkboxes as disabled.
> 
> In cast_collection I return the previous value instead of an empty array, so that a change that doesn't include that relation doesn't reset it.
> 
> The helper's Enum.reduce doesn't need an accumulator, and can be simplified to a map.

I'd accept a pull request for these if you wanted to submit one.

> If I always pipe a changeset into PhoenixMTM.Changeset.cast_collection(:tags, App.Repo, App.Tag), I need to preload(:tags) on every use of the changeset, even when if that relationship is not updated. I was surprised when the unit tests for my model for changeset.valid? were failing when there is no specific change that would require that relationship. Is this expected?

Not expected, but I likely never ran into this case. If you figure it out, I'd accept a pull request. If not, I'll look at it when I get some time.

Cheers.

**Comment by tute** [comment]
> I'd accept a pull request for these if you wanted to submit one.

Looks like it's been taken care of (https://github.com/adam12/phoenix_mtm/pull/2). Thanks!

**Comment by adam12** [comment]
> In cast_collection I return the previous value instead of an empty array, so that a change that doesn't include that relation doesn't reset it.

This is now the case in v0.3.0 - `cast_collection` won't modify the changeset if the association's key isn't in the params.

> I added a third argument to the helper's Enum.reduce, so that I can mark certain checkboxes as disabled.

I'd like to implement this somehow, perhaps a custom function that you can do whatever you wish. 

Along the lines of the following maybe?

``` elixir
def disabled_options(input_options) do
  if Enum.member?(["foobar", "baz"], input_options.value) do 
    Keyword.put(input_options, :disabled, true)
  else
    input_options
  end
end
```

``` elixir
<%= PhoenixMTM.Helpers.collection_checkboxes ..., input_opts_fn: &disabled_options/1 %>
```

Or perhaps even as simple as a `disabled` option similar to the `selected` option.
