### ISSUE TITLE
Custom wrapping/mapping of elements

### ISSUE THREAD

**Issue by adam12** [adam12/phoenix_mtm#10]
It would be nice to be able to provide a custom wrapper/mapper for the elements that we generate, to keep the creep of available formatting options to a minimum.

Work has already been started [here](https://github.com/adam12/phoenix_mtm/tree/custom-wrapper) and [here](https://github.com/adam12/phoenix_mtm/pull/5).

After some discussion, the best approach appears to be perhaps the ability to provide one of two functions.

`wrapper/1` - receive the label and input beside each other, and you are able to `wrap` it with a single tag (ie. using `content_tag`).

`mapper/6` - receive the input options, label options, helper options, and `map` the labels/inputs in any structure you want.

Open to discussion regarding this proposed feature.

(related to #5)

**Comment by sebastian** [comment]
Sounds great to me!
Thanks for all the work!

**Comment by adam12** [comment]
#11 updated with some actual documentation to show how this all functions.

Will be merging Monday, barring no show stopping comments from now until then.
